routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/logout', function(){
    Auth::logout();
    return redirect('/');
});

Route::middleware(['auth'])->group(function(){
    Route::resource('/tasks', 'App\Http\Controllers\TasksController');
    Route::put('/tasks/{task}/complete', 'App\Http\Controllers\TasksController@complete')->name('tasks.complete');
    Route::get('/completedTasks', 'App\Http\Controllers\TasksController@completedTasks')->name('tasks.completedTasks');
});

app/Models/Task.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'task',
        'status',
        'deadline',
        'completed_on'
    ];

    public function user(){
        return $this->belongsTo(User::class, 'user_id');
    }

    public function getDeadlineDateAttribute(){
        $data = $this->deadline;
        $newData = strtotime($data);
        $date = date('d M, Y | h:i A', $newData);
        return $date;
    }

    public function getCompletedOnDateAttribute(){
        $data = $this->completed_on;
        $newData = strtotime($data);
        $date = date('d M, Y | h:i A', $newData);
        return $date;
    }

    public function getisDeadlineExpiredAttribute(){
        if(date(Carbon::now()) > date(Carbon::parse($this->deadline))){
            return "Expired";
        }
        else{
            return "";
        }    
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function tasks(){
        return $this->hasMany(Task::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\tasks\CreateTaskRequest;
use App\Http\Requests\tasks\UpdateTaskRequest;
use App\Models\Task;
use Carbon\Carbon;
use DateTime;
use Facade\Ignition\Tabs\Tab;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class TasksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // pending tasks default krna baaki hai!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        $tasks = Task::all()->where('user_id', '=', Auth::id())->where('status', '=', 'pending');
        return view('tasks.index', compact([
            'tasks'
        ]));
    }

    public function completedTasks(){
        $tasks = Task::all()->where('status', '=', 'completed')->where('user_id', '=', Auth::id());
        return view('tasks.completed', compact([
            'tasks'
        ]));
    }

    public function complete(Task $task){
        $currentDateTime = Carbon::now()->toDateTimeString();

        $task->update([
            'status' => 'completed',
            'completed_on' => $currentDateTime
        ]);
        session()->flash('success', 'Task Completed!');
        return redirect(route('tasks.completedTasks'));
    }
    

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateTaskRequest $request)
    {
        try {
            $task = auth()->user()->tasks()->create([
                'task' => $request->task,
                'deadline' => $request->deadline
            ]);

    
        } catch (\Throwable $th) {
            dd($th);
        }
        
        session()->flash('success', 'Task Created!');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function show(Task $task)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function edit(Task $task)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTaskRequest $request, Task $task)
    {
        $data = request()->only([
            'task',
            'deadline'
        ]);

        $task->update($data);

        session()->flash('success', 'Task Updated!');
        return redirect(route('tasks.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\Response
     */

    public function trash(Task $task){
        
    }
    public function destroy(Task $task)
    {
        $task->forceDelete();
        session()->flash('success', "Task Deleted Successfully!");
        return redirect()->back();
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/_message.blade.php
<div class="row">
    <div class="col-md-12">
    @if(session()->has('success'))
        <div class="alert alert-success alert-dismissible fade show">
            {{ session()->get('success')}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true"></span>
            </button>
        </div>
    @endif
    @if(session()->has('error'))
        <div class="alert alert-danger alert-dismissible fade show">
            {{ session()->get('error')}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true"></span>
            </button>
        </div>
    @endif
    </div>
</div>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    @yield('page-level-styles')
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-dark shadow-sm">
            <div class="container">
                <a class="navbar-brand text-white" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                        
                            <li class="nav-item">
                                @if (Request::routeIs('tasks.index'))
                                    <a class="nav-link text-white" href="{{ route('tasks.completedTasks') }}">Completed Tasks</a>
                                @else
                                    <a class="nav-link text-white" href="{{ route('tasks.index') }}">Tasks</a>
                                @endif
                                
                            </li>
                            <li class="nav-item dropdown ml-3">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle text-white" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @auth
                <div class="container">

                    @include('layouts._message')
                    <div class="row">
                        <div class="col-md-3">
                            <ul class="list-group">
                                <li class="list-group-item">
                                <a href="{{ route('tasks.completedTasks') }}">Completed Tasks</a>  
                                </li>
                                
                            </ul>

                        
                        </div>
                        <div class="col-md-9">@yield('content')</div>
                    </div>
                    </div>   
            @else
            @yield('content')
            @endauth
        </main>
    </div>

     <!-- Scripts -->
     <script src="{{ asset('js/app.js') }}"></script>
    @yield('page-level-scripts')
</body>
</html>

resources/views/tasks/completed.blade.php
@extends('layouts.app')
@section('content')
<div class="row d-flex justify-content-center container">
    <div class="col-md-12">
        <div class="card-hover-shadow-2x mb-3 card">
            <div class="card-header-tab card-header">
                <div class="card-header-title font-size-lg text-capitalize font-weight-normal"><i class="fa fa-tasks"></i>&nbsp;Completed Task Lists</div>
            </div>
            <div class="scroll-area-sm">
                <perfect-scrollbar class="ps-show-limits">
                    <div style="position: static;" class="ps ps--active-y">
                        <div class="ps-content">
                            <ul class=" list-group list-group-flush">
                            @foreach ($tasks as $task)
                                <li class="list-group-item">
                                    <div class="todo-indicator bg-primary"></div>
                                    <div class="ml-2 widget-content p-0">
                                        <div class="widget-content-wrapper row">
                                            
                                            <div class="widget-content-left col-md-10">
                                                <div class="widget-heading text-left">{{ $task->task }}
                                                    @if ($task->is_deadline_expired)
                                                    <div class="badge badge-warning ml-2 p-1">
                                                    completed late
                                                    @else
                                                    <div class="badge badge-success ml-2 p-1">
                                                    completed on time   
                                                    @endif
                                                    </div>    
                                                </div>
                                                <div class="widget-subheading text-left text-danger">
                                                <label for="deadline">Completed On:</label>
                                                <i>{{ $task->completed_on_date }}</i>
                                                </div>
                                                
                                            </div>
                                            <div class="widget-content-right text-right col-md-2">  <button class="border-0 btn-transition btn btn-outline-danger" onclick= "displayModalForm({{ $task }})"  data-toggle="modal" data-target="#deleteModal"> <i class="fa fa-trash"></i> </button>
                                                 </div>
                                            
                                        </div>
                                    </div>
                                </li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                </perfect-scrollbar>
            </div>
        </div>
    </div>
</div>


<!-- Delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Delete Task</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                </div> 
                <form action="" method="POST" id="deleteForm">
                @csrf
                @method('DELETE')               
                <div class="modal-body">                    
                    <p>
                        Are you sure you want to Delete Task?
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger">Delete Task</button>
                </div>
                </form>
            </div>
        </div>
    </div>
<!-- /Delete Modal -->

@endsection

@section('page-level-scripts')
    <script type="text/javascript">
        function displayModalForm($task){
            var url = '/tasks/' + $task.id;
            $("#deleteForm").attr('action', url);
        }
    </script>
@endsection

resources/views/tasks/index.blade.php
@extends('layouts.app')
@section('content')
<div class="row d-flex justify-content-center container">
    <div class="col-md-12">
        <div class="card-hover-shadow-2x mb-3 card">
            <div class="card-header-tab card-header">
                <div class="card-header-title font-size-lg text-capitalize font-weight-normal"><i class="fa fa-tasks"></i>&nbsp;Task Lists</div>
            </div>
            <div class="scroll-area-sm">
                <perfect-scrollbar class="ps-show-limits">
                    <div style="position: static;" class="ps ps--active-y">
                        <div class="ps-content">
                            <ul class=" list-group list-group-flush">
                            @foreach ($tasks as $task)
                                <li class="list-group-item">
                                    <div class="todo-indicator bg-primary"></div>
                                    <div class="ml-2 widget-content p-0">
                                        <div class="widget-content-wrapper row">
                                            
                                            <div class="widget-content-left col-md-8">
                                                <div class="widget-heading text-left">{{ $task->task }}
                                                    <div class="badge badge-danger ml-2">{{ $task->is_deadline_expired }}</div>    
                                                </div>
                                                <div class="widget-subheading text-left text-danger">
                                                <label for="deadline">Deadline:</label>
                                                <i>{{ $task->deadline_date }}</i>
                                                </div>
                                                
                                            </div>
                                            <div class="widget-content-right text-right 
                                            col-md-4">
                                            <div class="row ml-5">
                                            <form action="{{ route('tasks.complete', $task) }}" method="POST" class="ml-5">
                                            @csrf
                                            @method('PUT')
                                             <button type="submit" class="border-0 btn-transition btn btn-outline-success"> <i class="fa fa-check"></i></button>
                                            </form>
                                              <button class="border-0 btn-transition btn btn-outline-danger" onclick= "displayModalForm({{ $task }})"  data-toggle="modal" data-target="#deleteModal"> <i class="fa fa-trash"></i> </button>
                                            <button class="border-0 btn-transition btn btn-outline-primary" onclick= "displayEditModalForm({{ $task }})"  data-toggle="modal" data-target="#editModal"><i class="fa fa-edit"></i></button>
                                            </div>
                                            </div>
                                            
                                        </div>
                                    </div>
                                </li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                </perfect-scrollbar>
            </div>
            <div class="d-block text-right card-footer"><button class="btn btn-primary" data-toggle="modal" data-target="#createModal">Add Task</button></div>
        </div>
    </div>
</div>

<!-- Create Modal -->

<div class="modal fade" id="createModal" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Add Task</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                </div> 
                <div class="modal-body">
                <form action="{{ route('tasks.store') }}" method="POST">
                @csrf
                    <div class="form-group">
                        <label for="task">Task:</label>
                        <input type="text" name="task" placeholder="Enter Task" value = "{{ old('task') }}" class="form-control {{ $errors->has('task') ? 'is-invalid' : '' }}">
                        @error('task')
                            <div class="text-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="deadline">Deadline:</label>
                        <input id="deadline" type="text" name="deadline" value="{{ old('deadline') }}" class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}">         
                        @error('deadline')
                            <div class="text-danger">{{ $message }}</div>
                        @enderror
                    </div>

                    <button type="submit" class="btn btn-outline-success">Add Task!</button>

                    @foreach($errors as $error)
    echo($error);
@endforeach
                </form>
                </div>
            </div>
        </div>
    </div>
<!-- /Create Modal -->

<!-- Edit Modal -->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Edit Task</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                </div> 
                <div class="modal-body"> 
                <form action="" method="POST" id="editForm">
                @csrf
                @method('PUT')
                    <div class="form-group">
                        <label for="task">Task:</label>
                        <input type="text" name="task" placeholder="Enter Task"
                        class="form-control {{ $errors->has('task') ? 'is-invalid' : '' }}">
                        @error('task')
                            <div class="text-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="deadline">Deadline:</label>
                        <input id="deadline" type="text" name="deadline" value="{{ old('deadline') }}" class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}">         
                        @error('deadline')
                            <div class="text-danger">{{ $message }}</div>
                        @enderror
                    </div>

                    <button type="submit" class="btn btn-outline-success">Edit Task!</button>

                </form>
                </div>
            </div>
        </div>
    </div>
<!-- /Edit Modal -->

<!-- Delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Delete Task</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                </div> 
                <form action="" method="POST" id="deleteForm">
                @csrf
                @method('DELETE')               
                <div class="modal-body">                    
                    <p>
                        Are you sure you want to Delete Task?
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger">Delete Task</button>
                </div>
                </form>
            </div>
        </div>
    </div>
<!-- /Delete Modal -->
@endsection


@section('content')
<div class="card">
            <div class="card-header">Add Task</div>
            <div class="card-body">
                
            </div>
        </div>

@endsection



@section('page-level-scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script>
    flatpickr("#deadline", {
            enableTime: true
        });
    </script>
    <script type="text/javascript">
        function displayModalForm($task){
            var url = '/tasks/' + $task.id;
            $("#deleteForm").attr('action', url);
        }

        function displayEditModalForm($task){
            var url = '/tasks/' + $task.id;
            $("#editForm").attr('action', url);

            $('#editForm input[name="task"]').val($task.task);
            $('#editForm input[name="deadline"]').val($task.deadline);
        }
    </script>
@endsection

@section('page-level-styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="{{  asset('css/app.css') }}">
 
@endsection